language: python
sudo: true
python:
  - "3.7.3"
cache: pip
install:
  - pip3 install -r requirements.txt
  - npm install -g jscpd
jobs:
  include:

    - stage: "Mutation Tests"
      name: "mutation testing using mutmut"
      script:
        - mutmut run > mutmut.log || true
        - mutmut junitxml --suspicious-policy=ignore --untested-policy=ignore > mutmut.xml
        - python3 test_resource/mutmut_parse.py --m 20 #Mutation (failure+disables+error) allowed 20% of total mutants

