language: python
sudo: true
python:
  - "3.7.3"
cache: pip
install:
  - pip3 install -r requirements.txt
  - npm install -g jscpd
jobs:
  include:
    - stage: "Static Analysis"
      name: "static analysis 'pylint & JSCPD'"
      script:
        - pylint guardrails/ test/ #Add jscpd gate once it is working in travis

    - stage: "Cyclomatic complexity"
      name: "cyclomatic complexity analysis with lizard"
      script:
          - python3 -m lizard guardrails -X> CC.xml
          - python3 test_resource/cyclo_gate.py --c 10 #Allowed cyclomatic complexity is less than 10

    - stage: "Dead Code"
      name: "Dead code analysis with  with vulture"
      script:
          - python3 -m vulture guardrails

    - stage: "Tests & Coverage"
      name: "Unit and functional test with coverage"
      script:
        - pytest test --cov-config=.coveragerc --cov=guardrails
        - coverage report --fail-under=90 #Coverage should be above 90%
      after_success: codecov

    - stage: "Mutation Tests"
      name: "mutation testing using mutmut"
      script:
        - mutmut --swallow-output run || true > mutmut.log
        - mutmut junitxml --suspicious-policy=ignore --untested-policy=ignore > mutmut.xml
        - python3 test_resource/mutmut_parse.py --m 20 #Mutation (failure+disables+error) allowed 20% of total mutants

