language: python
sudo: true
python:
  - "3.7.3"
cache: pip
install:
  - pip3 install -r requirements.txt
  - npm install -g jscpd
jobs:
  include:
    - stage: "Tests & Coverage"
      name: "Unit and functional test with coverage"
      script:
        - python3 -m pytest test -v

